#!/bin/bash

if [ $# -lt 1 ]; then
   echo "Usage: $0 patient[ID] patient[ID2] ..."
   exit 1
fi
MUT=/costellolab/data4/LG3_hg38_output/LG4/mutations
for P in $@
do
   echo "P${P} : "
   for HS in $(ls -1 ${MUT}/Patient${P}_mutect2/*.filtered.vcf)
   do
      echo "${HS}" | cut -f8- -d/
      grep ID=Mutect2 ${HS} | tr ' ' '\n' | grep -A1 intervals | tail -n +2 | cut -f5- -d/
   done
done | sort 
#done | sort -ru

